apiVersion: v1
kind: Service
metadata:
  name: admin-laravel-svc
  labels:
    app: admin-laravel
spec:
  type: NodePort
  selector:
    app: admin-laravel
  ports:
  - name: admin-laravel-svc
    port: 80
    targetPort: 80