apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-node
spec:
  selector:
    matchLabels:
      app: analytics-node
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  template:
    metadata:
      labels:
        app: analytics-node
    spec:
      containers:
        - name: analytics-node
          image: XXXXXXXXXXXX.dkr.ecr.ap-south-1.amazonaws.com/analytics-node-prod
          envFrom:
            - configMapRef:
                name: backend-analytics-node-configmap
            - secretRef:
                name: analytics-node-secret
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000