apiVersion: v1
kind: Service
metadata:
  name: analytics-node-svc
  labels:
    app: analytics-node
spec:
  type: NodePort
  selector:
    app: analytics-node
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000