apiVersion: v1
kind: Service
metadata:
  name: widgets-cors-svc
  labels:
    app: widgets-cors
spec:
  type: NodePort
  selector:
    app: widgets-cors
  ports:
  - name: widgets-cors-svc
    port: 80
    targetPort: 11001