apiVersion: v1
kind: Service
metadata:
  name: superadmin-svc
  labels:
    app: superadmin
spec:
  type: NodePort
  selector:
    app: superadmin
  ports:
  - name: superadmin-svc
    port: 80
    targetPort: 80