namespace: widgets
resources:
  - ../base/widgets
  - ../base/widgets-cors
  - frontend-widgets-ingress.yaml
  - backend-widgets-cors-ingress.yaml
patchesStrategicMerge:
  - frontend-widgets-deploy.yaml
  - backend-widgets-cors-deploy.yaml
images:
  - name: XXXXXXXXXXXX.dkr.ecr.ap-south-1.amazonaws.com/widgets-prod
    newTag: '8'
  - name: 472598545260.dkr.ecr.ap-south-1.amazonaws.com/widgets-cors-prod
    newTag: '8'