apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs
spec:
  selector:
    matchLabels:
      app: vuejs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels: 
        app: vuejs
    spec:
      containers:
        - name: vuejs
          image: XXXXXXXXXXXX.dkr.ecr.ap-south-1.amazonaws.com/vuejs-prod
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: vuejs