apiVersion: v1
kind: Service
metadata:
  name: widgets-svc
  labels:
    app: widgets
spec:
  type: NodePort
  selector:
    app: widgets
  ports:
  - name: widgets-svc
    port: 80
    targetPort: 80