apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortening
spec:
  selector:
    matchLabels:
      app: url-shortening
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: url-shortening
    spec:
      containers:
        - name: url-shortening
          image: XXXXXXXXXXXX.dkr.ecr.ap-south-1.amazonaws.com/url-shortening-prod
          envFrom:
            - configMapRef:
                name: backend-url-shortening-configmap
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000