apiVersion: v1
kind: Service
metadata:
  name: url-shortening-svc
  labels:
    app: url-shortening
spec:
  type: NodePort
  selector:
    app: url-shortening
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000